version: "3.8"
services:
  wizarr:
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr
    ports:
    - 5690:5690
    volumes:
      - ./data:/data/database
    environment:
      - APP_URL=https://join.domain.com
      - DISABLE_BUILTIN_AUTH=false #Set to true ONLY if you are using another auth provider (Authelia, Authentik, etc)
      - ALLOW_BUG_REPORTING=true #Helps me fix bugs, but you can disable it if you want! I use Sentry.io for this.

  watchtower: #Optional but recommended, as Wizarr is still in development and will be updated frequently
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: wizarr --interval 30
